- id: '1691842594162'
  alias: Hall light (Motion)
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      light_target:
        device_id: 874292888d49081c268ee8e27b9c2605
      motion_entity: binary_sensor.front_door_motion_sensor_motion
- id: '1691847438428'
  alias: Turn sleep machines off (Daily schedule)
  description: ''
  triggers:
  - at: '10:10:00'
    trigger: time
  conditions: []
  actions:
  - type: turn_off
    device_id: 029f6368dd8596d462f1f686841d99a3
    entity_id: b554a8e128a23d0afaa11f767f13b54a
    domain: switch
  - type: turn_off
    device_id: 029f6368dd8596d462f1f686841d99a3
    entity_id: ab2a5cf760d717c374b499a2e4363cc5
    domain: switch
  - data:
      message: Sleep machine off
      title: Automation
    action: notify.mobile_app_jon_iphone
  mode: single
- id: '1691848308714'
  alias: Amaya is up (NFC)
  description: ''
  trigger:
  - platform: tag
    tag_id: b1df81f5-ba8f-4ee2-8a58-cbfee709cf20
  condition: []
  action:
  - type: turn_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
    brightness_pct: 20
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.bedside_lamp_toggle
  mode: single
- id: '1691957631259'
  alias: Run bathroom fan (NFC)
  description: For 30 minutes
  trigger:
  - platform: tag
    tag_id: 61d92c29-9aa4-46e6-acff-eae3a0eec044
  condition: []
  action:
  - type: turn_on
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: 0e50149fed819e0d0cd7d540173f3ada
    domain: light
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: 0e50149fed819e0d0cd7d540173f3ada
    domain: light
  mode: single
- id: '1691961487180'
  alias: ' Turn on desk lights (NFC)'
  description: ''
  trigger:
  - platform: tag
    tag_id: aee9d8aa-2b91-44df-bb4f-5c669b2d9f23
  condition: []
  action:
  - type: turn_on
    device_id: 27a6898e8c28c0ed2da7ca3cf2828467
    entity_id: 22fdde003d535304af87fcafd5f75bb2
    domain: switch
  - type: turn_on
    device_id: 7a77d0feeed093133858833de346247f
    entity_id: be5cff5bca73a427a6cdc2dea999641a
    domain: switch
  mode: single
- id: '1691961708012'
  alias: Wind down (NFC)
  description: ''
  triggers:
  - tag_id: 7497d748-45c1-4be8-9b0f-e511dc166109
    trigger: tag
  conditions: []
  actions:
  - type: turn_off
    device_id: 8f3e53dcf02e7c97e18f16fb8aa48d1c
    entity_id: ec7c26ce9ce900ada90334bfcf92cd96
    domain: light
  - type: turn_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
  - type: turn_on
    device_id: 029f6368dd8596d462f1f686841d99a3
    entity_id: b554a8e128a23d0afaa11f767f13b54a
    domain: switch
  mode: single
- id: '1691961908252'
  alias: Turn off all lights (NFC)
  description: ''
  trigger:
  - platform: tag
    tag_id: b4fc42fa-294f-4fef-80d4-2e88fc9149f5
  condition: []
  action:
  - service: light.turn_off
    entity_id: all
  - type: turn_off
    device_id: 27a6898e8c28c0ed2da7ca3cf2828467
    entity_id: 22fdde003d535304af87fcafd5f75bb2
    domain: switch
  - type: turn_off
    device_id: 7a77d0feeed093133858833de346247f
    entity_id: be5cff5bca73a427a6cdc2dea999641a
    domain: switch
  mode: single
- id: '1692386498657'
  alias: Jon's desk light switch
  description: ''
  trigger:
  - device_id: 9b9cd36aa91d63bde113aac5d20af4a5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: 27a6898e8c28c0ed2da7ca3cf2828467
    entity_id: 22fdde003d535304af87fcafd5f75bb2
    domain: switch
  mode: single
- id: '1692386610340'
  alias: Estela's desk light switch
  description: ''
  trigger:
  - device_id: 9b9cd36aa91d63bde113aac5d20af4a5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - type: toggle
    device_id: 7a77d0feeed093133858833de346247f
    entity_id: be5cff5bca73a427a6cdc2dea999641a
    domain: switch
  mode: single
- id: '1692387270822'
  alias: Bedside lamp ON (60 brightness)
  description: Press once for 60% brightness
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition:
  - condition: state
    entity_id: input_boolean.bedside_lamp_toggle
    state: 'off'
  action:
  - type: turn_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
    brightness_pct: 60
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.bedside_lamp_toggle
  mode: single
- id: '1692387308467'
  alias: Bedroom's fan switch
  description: ''
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - service: fan.toggle
    data: {}
    target:
      device_id: 4c236a9e9d1f3d83850458e750d0a64b
  mode: single
- id: '1692439674398'
  alias: Bedroom's fan oscilation
  description: ''
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_2
  condition: []
  action:
  - service: fan.oscillate
    data:
      oscillating: true
    target:
      device_id: 4c236a9e9d1f3d83850458e750d0a64b
  mode: single
- id: '1692454903328'
  alias: You've got mail (Motion)
  description: ''
  triggers:
  - type: motion
    device_id: cddb8b9d37d9b2eeb8aded7e2ca691e5
    entity_id: 2c3c4208a8b03613bd6a2d28cb9bd542
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - parallel:
    - data:
        message: You've got mail!
        title: Mailbox
      action: notify.mobile_app_jon_iphone
    - data:
        message: You've got mail!
        title: Mailbox
      action: notify.mobile_app_tablet_ags2_w09
  mode: single
- id: '1693585613915'
  alias: Low battery on sensors notification
  description: ''
  use_blueprint:
    path: gmlupatelli/low_battery_notification.yaml
    input:
      actions:
      - parallel:
        - service: notify.mobile_app_jon_iphone
          data:
            title: Low battery on sensors
            message: 'The following sensors are running out of battery: {{sensors}}'
        - service: notify.mobile_app_tablet_ags2_w09
          data:
            title: Low battery on sensors
            message: 'The following sensors are running out of battery: {{sensors}}'
        - service: notify.persistent_notification
          data:
            title: Low battery on sensors
            message: 'The following sensors are running out of battery: {{sensors}}'
- id: '1693586144323'
  alias: Smoke alert
  description: ''
  use_blueprint:
    path: user-x-adm/smoke-alert-en.yaml
    input:
      sensor:
      - binary_sensor.smoke_sensor_hall_smoke
      - binary_sensor.smoke_sensor_office_smoke
      - binary_sensor.smoke_sensor_living_room_smoke
      text: ' has detected Smoke! Call 150 (Fire brigade)!'
- id: '1693640955673'
  alias: Tablet battery notification
  description: ''
  triggers:
  - type: battery_level
    device_id: a1bd579d0d06464d81c358e5a8e61325
    entity_id: ad3cd6cbac5b5afda9d9763b4229053a
    domain: sensor
    below: 20
    trigger: device
  conditions: []
  actions:
  - data:
      title: Tablet running out of battery
      message: Time to charge the tablet!
    action: notify.mobile_app_jon_iphone
  - action: notify.mobile_app_iphone_de_estela
    metadata: {}
    data:
      title: Tablet running out of battery
      message: Time to charge the tablet!
  mode: single
- id: '1694340353314'
  alias: Leaving Home NFC (arm away)
  description: Arms the alarm when leaving home
  trigger:
  - platform: tag
    tag_id: 0b0e1a57-e751-43f5-a884-611e0098a749
  condition:
  - condition: state
    entity_id: input_boolean.alarm_toggle
    state: 'off'
  action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      code: '7311'
    target:
      entity_id: alarm_control_panel.alarmo
  mode: single
- id: '1694693354677'
  alias: Hall lights (switches)
  description: Switches for Hall lights
  trigger:
  - device_id: 4066dcaf920b23439f31b89dccc8a2a5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  - device_id: 8e8b87aee8bc614e6c8c52ae3a988815
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: 874292888d49081c268ee8e27b9c2605
    entity_id: 95009e85bae32e8f32506b1e22b1a70c
    domain: light
  mode: single
- id: '1694722705907'
  alias: Kitchen counter LED strip switch
  description: ''
  trigger:
  - device_id: b5881933db6e641096d92922d75edabf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: 17162c8a1b34b80ab8c6a06bdc90969c
    entity_id: 5888154a072713f62c48b0e400d291ca
    domain: light
  mode: single
- id: '1694817540849'
  alias: Bedside lamp OFF (switch)
  description: ''
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition:
  - condition: state
    entity_id: input_boolean.bedside_lamp_toggle
    state: 'on'
  action:
  - type: turn_off
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.bedside_lamp_toggle
  mode: single
- id: '1694817661674'
  alias: Bedside lamp ON (5 brightness)
  description: Double click for 5% brightness
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_1
  condition: []
  action:
  - type: turn_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
    brightness_pct: 5
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.bedside_lamp_toggle
  mode: single
- id: '1694861106361'
  alias: Reset TV - NFC
  description: Reset the Samsung TV which often starts misbehaving
  triggers:
  - tag_id: 3c2dde61-d82c-4d02-b20d-288dd2856421
    trigger: tag
  conditions: []
  actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  mode: single
- id: '1695096160681'
  alias: Bedside lamp ON sets input ON
  description: For when the lamp is turned on physically
  trigger:
  - platform: device
    type: turned_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.bedside_lamp_toggle
  mode: single
- id: '1695096240488'
  alias: Bedside lamp OFF sets input OFF
  description: For when the lamp is turned on physically
  trigger:
  - platform: device
    type: turned_off
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
  condition: []
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.bedside_lamp_toggle
  mode: single
- id: '1695165236137'
  alias: Ready to sleep
  description: ''
  triggers: []
  conditions: []
  actions:
  - type: turn_on
    device_id: 029f6368dd8596d462f1f686841d99a3
    entity_id: b554a8e128a23d0afaa11f767f13b54a
    domain: switch
  - type: turn_on
    device_id: 029f6368dd8596d462f1f686841d99a3
    entity_id: ab2a5cf760d717c374b499a2e4363cc5
    domain: switch
  - entity_id: all
    action: light.turn_off
  mode: single
- id: '1713084722052'
  alias: Bathroom fan on if door closed
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: c59a2665845314328891a387d5aa23f1
    entity_id: d208a439f4d1de5612d31b08fe70897d
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: c4679ea464275c334d51c92466416432
    domain: light
  action:
  - type: turn_on
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: 0e50149fed819e0d0cd7d540173f3ada
    domain: light
  mode: single
- id: '1714767642612'
  alias: Baby's bath
  description: ''
  triggers: []
  conditions: []
  actions:
  - entity_id: all
    enabled: false
    action: light.turn_off
  - type: turn_on
    device_id: 029f6368dd8596d462f1f686841d99a3
    entity_id: b554a8e128a23d0afaa11f767f13b54a
    domain: switch
  - type: turn_on
    device_id: 029f6368dd8596d462f1f686841d99a3
    entity_id: ab2a5cf760d717c374b499a2e4363cc5
    domain: switch
  - type: turn_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
    brightness_pct: 60
  - type: turn_on
    device_id: 8f3e53dcf02e7c97e18f16fb8aa48d1c
    entity_id: ec7c26ce9ce900ada90334bfcf92cd96
    domain: light
    enabled: true
  - type: turn_on
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: 0e50149fed819e0d0cd7d540173f3ada
    domain: light
  - type: turn_on
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: c4679ea464275c334d51c92466416432
    domain: light
  - type: turn_on
    device_id: 17162c8a1b34b80ab8c6a06bdc90969c
    entity_id: 5888154a072713f62c48b0e400d291ca
    domain: light
    brightness_pct: 100
  mode: single
- id: '1734094292918'
  alias: Open shutters after sunrise
  description: Open shutters after sunrise
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - device_id: f98d06aeb44a5b9a6d822ba9a77a22c6
    domain: cover
    entity_id: 35aebba38e8128762776d3ee2bb4fddc
    type: close
  - device_id: 30f3bea3ba2eedf57fe252950b69a03f
    domain: cover
    entity_id: b7289e0524cd2ce2c8e54560a107fb11
    type: close
    enabled: false
  mode: single
- id: '1734094507472'
  alias: Close shutters after sunset
  description: Close shutters after sunset
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - device_id: f98d06aeb44a5b9a6d822ba9a77a22c6
    domain: button
    entity_id: e7010a7300c60274af32e55aa8f5e8b6
    type: press
  - device_id: 30f3bea3ba2eedf57fe252950b69a03f
    domain: button
    entity_id: 396bfc8c42f7722b3286779dcaaff062
    type: press
    enabled: false
  mode: single
- id: '1735154738113'
  alias: Turn bedside lamp off when in bed
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.withings_in_bed
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions:
  - condition: time
    after: '22:00:00'
    before: 05:00:00
    weekday:
    - sun
    - sat
    - fri
    - thu
    - wed
    - mon
    - tue
  actions:
  - type: turn_off
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
  mode: single
- id: '1735155380420'
  alias: Turn lights on when preparing for the gym
  description: Turn some of the lights on when leaving bed and preparing to go to
    the gym in the morning
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.withings_in_bed
    to: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 10
    from: 'on'
  conditions:
  - condition: time
    after: 05:00:00
    before: 07:00:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - type: turn_on
    device_id: 7a77d0feeed093133858833de346247f
    entity_id: be5cff5bca73a427a6cdc2dea999641a
    domain: switch
  - type: turn_on
    device_id: 17162c8a1b34b80ab8c6a06bdc90969c
    entity_id: 5888154a072713f62c48b0e400d291ca
    domain: light
  mode: single
- id: '1735158621340'
  alias: Open Office shutter when office window opens
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.office_window_1_opening
    to: 'on'
  conditions: []
  actions:
  - device_id: f98d06aeb44a5b9a6d822ba9a77a22c6
    domain: cover
    entity_id: 35aebba38e8128762776d3ee2bb4fddc
    type: close
  mode: single
- id: '1735158803140'
  alias: Open Children's bedroom shutter when window opens
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_9
    to: 'on'
  conditions: []
  actions:
  - device_id: 30f3bea3ba2eedf57fe252950b69a03f
    domain: cover
    entity_id: b7289e0524cd2ce2c8e54560a107fb11
    type: close
  mode: single
- id: '1735209040972'
  alias: Turn dehumidifier on when humidity is too high
  description: ''
  triggers:
  - type: humidity
    device_id: 98551d502342f3f9002cedc5b3be90f0
    entity_id: b377a919620fc2999ce5e9972760b223
    domain: sensor
    trigger: device
    above: 57
  conditions: []
  actions:
  - type: turn_on
    device_id: 8ad864df05a51c2be3133cdb2460e425
    entity_id: 7ab10edf555f159316a05c62447eb434
    domain: humidifier
  mode: single
- id: '1735209285489'
  alias: Turn dehumidifier off when humidity is not high anymore
  description: ''
  triggers:
  - type: humidity
    device_id: 98551d502342f3f9002cedc5b3be90f0
    entity_id: b377a919620fc2999ce5e9972760b223
    domain: sensor
    trigger: device
    below: 46
  conditions: []
  actions:
  - type: turn_off
    device_id: 8ad864df05a51c2be3133cdb2460e425
    entity_id: 7ab10edf555f159316a05c62447eb434
    domain: humidifier
  - action: notify.mobile_app_jon_iphone
    metadata: {}
    data:
      title: Dehumidifier
      message: Remove water from the dehumidifier!
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: Remove water from the dehumidifier!
      title: Dehumidifier
  mode: single
