- id: '1691842594162'
  alias: Hall light (Motion)
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      light_target:
        device_id: 874292888d49081c268ee8e27b9c2605
      motion_entity: binary_sensor.front_door_motion_sensor_motion
- id: '1691847438428'
  alias: Turn sleep machine off (Daily schedule)
  description: ''
  trigger:
  - platform: time
    at: '10:10:00'
  condition: []
  action:
  - type: turn_off
    device_id: 17934490a668e65a95553640b6008c91
    entity_id: 43d1d1a68fd918946da31e901540b4f6
    domain: switch
  - service: notify.mobile_app_jon_iphone
    data:
      message: Sleep machine off
      title: Automation
  mode: single
- id: '1691848308714'
  alias: Amaya is up (NFC)
  description: ''
  trigger:
  - platform: tag
    tag_id: b1df81f5-ba8f-4ee2-8a58-cbfee709cf20
  condition: []
  action:
  - type: turn_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
    brightness_pct: 20
  mode: single
- id: '1691957631259'
  alias: Run bathroom fan (NFC)
  description: For 5 minutes
  trigger:
  - platform: tag
    tag_id: 61d92c29-9aa4-46e6-acff-eae3a0eec044
  condition: []
  action:
  - type: turn_on
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: 0e50149fed819e0d0cd7d540173f3ada
    domain: light
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 53b0f001e380e99402db43c79099a703
    entity_id: 0e50149fed819e0d0cd7d540173f3ada
    domain: light
  mode: single
- id: '1691960330122'
  alias: Movie Night (NFC)
  description: ''
  trigger:
  - platform: tag
    tag_id: 4a235380-62f0-4024-8405-2a3937920ae2
  condition: []
  action:
  - type: turn_on
    device_id: 0d0dd790e6a8e73a56a5e35c841d9cec
    entity_id: 649c7ae0063c4fda1b15913be3170e2f
    domain: switch
  - type: turn_on
    device_id: 7de44226570dfab57e466bc22c4dc3f8
    entity_id: fa70a94ea559a0c67eb11bb45d1c0496
    domain: remote
  - service: media_player.turn_on
    data: {}
    target:
      device_id: 7de44226570dfab57e466bc22c4dc3f8
  - type: turn_off
    device_id: 0149505f3839e969313b3fdcc322bde0
    entity_id: 6cc5dbb9a3056a17f400b64c7162dd67
    domain: light
  - type: turn_off
    device_id: f9586f90a966023e326b2c40268d4c29
    entity_id: c775fd444d108ed2e8c6aab77313a4f1
    domain: light
  - type: turn_on
    device_id: 17162c8a1b34b80ab8c6a06bdc90969c
    entity_id: 5888154a072713f62c48b0e400d291ca
    domain: light
  mode: single
- id: '1691961487180'
  alias: ' Turn on desk lights (NFC)'
  description: ''
  trigger:
  - platform: tag
    tag_id: aee9d8aa-2b91-44df-bb4f-5c669b2d9f23
  condition: []
  action:
  - type: turn_on
    device_id: d2b26d2cbdce70789cae28fbe7fade34
    entity_id: 2c6e19e149f391173709c66c3ea2edd4
    domain: light
  - type: turn_on
    device_id: 384de0aef30160c4cd7c0a16a2bacc6e
    entity_id: 4906acf6edf4c08abb9bff70c1ca61f4
    domain: switch
  mode: single
- id: '1691961708012'
  alias: Wind down (NFC)
  description: ''
  trigger:
  - platform: tag
    tag_id: 7497d748-45c1-4be8-9b0f-e511dc166109
  condition: []
  action:
  - type: turn_off
    device_id: 8f3e53dcf02e7c97e18f16fb8aa48d1c
    entity_id: ec7c26ce9ce900ada90334bfcf92cd96
    domain: light
  - type: turn_on
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
  - type: turn_on
    device_id: 17934490a668e65a95553640b6008c91
    entity_id: 43d1d1a68fd918946da31e901540b4f6
    domain: switch
  mode: single
- id: '1691961908252'
  alias: Turn off all lights (NFC)
  description: ''
  trigger:
  - platform: tag
    tag_id: b4fc42fa-294f-4fef-80d4-2e88fc9149f5
  condition: []
  action:
  - service: light.turn_off
    entity_id: all
  mode: single
- id: '1692386498657'
  alias: Jon's desk light switch
  description: ''
  trigger:
  - device_id: 9b9cd36aa91d63bde113aac5d20af4a5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: d2b26d2cbdce70789cae28fbe7fade34
    entity_id: 2c6e19e149f391173709c66c3ea2edd4
    domain: light
  mode: single
- id: '1692386610340'
  alias: Estela's desk light switch
  description: ''
  trigger:
  - device_id: 9b9cd36aa91d63bde113aac5d20af4a5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - type: toggle
    device_id: 384de0aef30160c4cd7c0a16a2bacc6e
    entity_id: 4906acf6edf4c08abb9bff70c1ca61f4
    domain: switch
  mode: single
- id: '1692387270822'
  alias: Bedside light switch
  description: ''
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: dd62ddc5b747cdaf29a815419cb989f4
    entity_id: 2e486700a34beb8e888e44c0b89665ba
    domain: light
  mode: single
- id: '1692387308467'
  alias: Bedroom's fan switch
  description: ''
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - service: fan.toggle
    data: {}
    target:
      device_id: 4c236a9e9d1f3d83850458e750d0a64b
  mode: single
- id: '1692439674398'
  alias: Bedroom's fan oscilation
  description: ''
  trigger:
  - device_id: d0572f7c033a5d76c64c1a4eb88daeaf
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: button_2
  condition: []
  action:
  - service: fan.oscillate
    data:
      oscillating: true
    target:
      device_id: 4c236a9e9d1f3d83850458e750d0a64b
  mode: single
- id: '1692454903328'
  alias: You've got mail (Motion)
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: cddb8b9d37d9b2eeb8aded7e2ca691e5
    entity_id: 2c3c4208a8b03613bd6a2d28cb9bd542
    domain: binary_sensor
  condition: []
  action:
  - parallel:
    - service: notify.mobile_app_jon_iphone
      data:
        message: You've got mail!
        title: Mailbox
    - service: notify.mobile_app_sm_g973f
      data:
        title: Mailbox
        message: You've got mail!
    - service: notify.mobile_app_tablet_ags2_w09
      data:
        message: You've got mail!
        title: Mailbox
    - service: notify.alexa_media_kitchen_s_alexa
      data:
        message: You've got mail!
    - service: notify.alexa_media_office_s_alexa
      data:
        message: You've got mail!
  mode: single
- id: '1693585613915'
  alias: Low battery on sensors notification
  description: ''
  use_blueprint:
    path: gmlupatelli/low_battery_notification.yaml
    input:
      actions:
      - parallel:
        - service: notify.mobile_app_jon_iphone
          data:
            title: Low battery on sensors
            message: 'The following sensors are running out of battery: {{sensors}}'
        - service: notify.mobile_app_tablet_ags2_w09
          data:
            title: Low battery on sensors
            message: 'The following sensors are running out of battery: {{sensors}}'
        - service: notify.persistent_notification
          data:
            title: Low battery on sensors
            message: 'The following sensors are running out of battery: {{sensors}}'
- id: '1693585840136'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      - update.pi_hole_core_update_available
      - update.pi_hole_ftl_update_available
      - update.pi_hole_web_update_available
      mobile_app_device: 39fbc6fe1a86add10fd919a29b74ad03
      send_to_ha: true
- id: '1693586144323'
  alias: Smoke alert
  description: ''
  use_blueprint:
    path: user-x-adm/smoke-alert-en.yaml
    input:
      sensor:
      - binary_sensor.smoke_sensor_hall_smoke
      - binary_sensor.smart_siren_smoke
      - binary_sensor.smoke_sensor_office_smoke
      - binary_sensor.smoke_sensor_living_room_smoke
      text: ' has detected Smoke! Call 150 (Fire brigade)!'
- id: '1693640955673'
  alias: Tablet battery notification
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: a1bd579d0d06464d81c358e5a8e61325
    entity_id: ad3cd6cbac5b5afda9d9763b4229053a
    domain: sensor
    below: 20
  condition: []
  action:
  - service: notify.mobile_app_jon_iphone
    data:
      title: Tablet running out of battery
      message: Time to charge the tablet!
  - service: notify.mobile_app_sm_g973f
    data:
      title: Tablet running out of battery
      message: Time to charge the tablet!
  mode: single
- id: '1694340353314'
  alias: Leaving Home NFC (arm away)
  description: Arms the alarm when leaving home
  trigger:
  - platform: tag
    tag_id: 0b0e1a57-e751-43f5-a884-611e0098a749
  condition:
  - condition: state
    entity_id: input_boolean.alarm_toggle
    state: 'off'
  action:
  - service: alarm_control_panel.alarm_arm_away
    data:
      code: '7311'
    target:
      entity_id: alarm_control_panel.alarmo
  mode: single
- id: '1694375599058'
  alias: Jon-iPhone finished charging
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: 39fbc6fe1a86add10fd919a29b74ad03
    entity_id: f6089c7b80e6f5f5c872af81c0063d24
    domain: sensor
    above: 99
  condition: []
  action:
  - service: notify.mobile_app_jon_iphone
    data:
      message: iPhone finished charging!
      title: Jon-iPhone charger
  mode: single
- id: '1694693354677'
  alias: Hall lights (switches)
  description: Switches for Hall lights
  trigger:
  - device_id: 4066dcaf920b23439f31b89dccc8a2a5
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  - device_id: 8e8b87aee8bc614e6c8c52ae3a988815
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: 874292888d49081c268ee8e27b9c2605
    entity_id: 95009e85bae32e8f32506b1e22b1a70c
    domain: light
  mode: single
- id: '1694722705907'
  alias: Kitchen counter LED strip switch
  description: ''
  trigger:
  - device_id: b5881933db6e641096d92922d75edabf
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: 17162c8a1b34b80ab8c6a06bdc90969c
    entity_id: 5888154a072713f62c48b0e400d291ca
    domain: light
  mode: single
- id: '1694724431165'
  alias: Bathroom LED strip ON (Motion)
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 4ae8515c94d49b4afaa2d04cbb5b4b94
    entity_id: 7cc73f086e231599008fb141b46c9e93
    domain: binary_sensor
  condition:
  - condition: sun
    after: sunset
  action:
  - type: turn_on
    device_id: 650cda6559668b39b1a3bd9828de9d3e
    entity_id: b56e5b0ccfb74b74713884bc168f0747
    domain: light
    brightness_pct: 100
  mode: single
- id: '1694724531249'
  alias: Bathroom LED strip OFF (Motion)
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 4ae8515c94d49b4afaa2d04cbb5b4b94
    entity_id: 7cc73f086e231599008fb141b46c9e93
    domain: binary_sensor
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 650cda6559668b39b1a3bd9828de9d3e
    entity_id: b56e5b0ccfb74b74713884bc168f0747
    domain: light
  mode: single
