# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: worldclock
    name: Prague
    time_zone: Europe/Prague
  - platform: worldclock
    name: Rio
    time_zone: America/Sao_Paulo

rest_command:
  voice_monkey:
    method: POST
    url: "http://192.168.0.68:9000/triggers"
    payload: '{"device":"{{device}}"}'
    content_type: "application/json; charset=utf-8"

climate:
  - platform: miheater
    host: 192.168.0.52
    token: !secret miheater_token
    name: xiaomi_heater
    model: zhimi.heater.mc2

