# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#sensor:
#  - platform: worldclock
#    name: Prague
#    time_zone: Europe/Prague
#  - platform: worldclock
#    name: Rio
#    time_zone: America/Sao_Paulo

#climate:
#  - platform: miheater
#    host: 192.168.0.52
#   token: !secret miheater_token
#    name: xiaomi_heater
#    model: zhimi.heater.mc2

homeassistant:
  auth_mfa_modules:
    - type: totp

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.68

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token
